"""
convert.py — quantize the trained Keras model to a fully int8 TFLite model
(required for TFLite-Micro on the ESP32) and emit model_data.h / model_data.cc
ready to be compiled straight into the firmware.

Usage:
    python convert.py

Requires that train.py has already produced:
    training/artifacts/naad_kws.keras
    training/artifacts/feature_mean.npy
    training/artifacts/feature_std.npy
"""

import os

import numpy as np
import tensorflow as tf

from audio_utils import augment, extract_mfcc, list_wavs, load_noise_clips, load_wav
from config import (
    INPUT_SHAPE,
    KERAS_MODEL_PATH,
    MODEL_DATA_CC,
    MODEL_DATA_H,
    MODEL_OUT_DIR,
    NEG_DIR,
    NEG_NOISE_DIR,
    POS_DIR,
    TFLITE_INT8_PATH,
)


def representative_dataset_gen(num_samples=200):
    """
    Full-integer quantization needs real example inputs to calibrate the
    activation ranges layer by layer. We reuse the training clips (with a
    bit of augmentation for variety) rather than random noise, since random
    noise gives a poor calibration range for real speech features.
    """
    mean = float(np.load(os.path.join(MODEL_OUT_DIR, "feature_mean.npy")))
    std = float(np.load(os.path.join(MODEL_OUT_DIR, "feature_std.npy")))

    pos_files = list_wavs(POS_DIR, recursive=False)
    neg_files = [f for f in list_wavs(NEG_DIR, recursive=True)
                 if os.path.dirname(f) != NEG_NOISE_DIR]
    noise_clips = load_noise_clips(NEG_NOISE_DIR)

    all_files = pos_files + neg_files
    if not all_files:
        raise RuntimeError("No wav files found to build the representative "
                            "dataset — run this after populating dataset/.")

    rng = np.random.default_rng(42)
    rng.shuffle(all_files)
    picked = (all_files * (num_samples // len(all_files) + 1))[:num_samples]

    for f in picked:
        try:
            audio = load_wav(f)
            if rng.random() < 0.5:
                audio = augment(audio, noise_clips)
            feats = extract_mfcc(audio)
            feats = (feats - mean) / (std + 1e-8)
            feats = feats[np.newaxis, ..., np.newaxis].astype(np.float32)
            yield [feats]
        except Exception as e:
            print(f"  [warn] skipping {f} in calibration set: {e}")


def convert_to_int8():
    model = tf.keras.models.load_model(KERAS_MODEL_PATH)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen
    # Force full int8: every op, input and output quantized. This is what
    # TFLite-Micro on ESP32 expects (no float fallback kernels bloating flash).
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    os.makedirs(MODEL_OUT_DIR, exist_ok=True)
    with open(TFLITE_INT8_PATH, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"Saved int8 TFLite model -> {TFLITE_INT8_PATH}  ({size_kb:.1f} KB)")
    if size_kb > 100:
        print("[warn] model is larger than expected for this problem's "
              "budget — consider shrinking filters in train.py's build_model().")

    return tflite_model


def emit_c_arrays(tflite_bytes):
    var_name = "g_naad_kws_model_data"
    n = len(tflite_bytes)

    header = f"""\
// AUTO-GENERATED by training/convert.py — do not edit by hand.
// Regenerate with: python convert.py
#ifndef NAAD_MODEL_DATA_H_
#define NAAD_MODEL_DATA_H_

#include <cstdint>

extern const unsigned char {var_name}[];
extern const unsigned int {var_name}_len;

#endif  // NAAD_MODEL_DATA_H_
"""

    lines = []
    for i in range(0, n, 12):
        chunk = tflite_bytes[i:i + 12]
        lines.append(", ".join(f"0x{b:02x}" for b in chunk))
    body = ",\n  ".join(lines)

    source = f"""\
// AUTO-GENERATED by training/convert.py — do not edit by hand.
// Model: naad_kws_int8.tflite ({n} bytes)
#include "model_data.h"

alignas(16) const unsigned char {var_name}[] = {{
  {body}
}};

const unsigned int {var_name}_len = {n};
"""

    os.makedirs(os.path.dirname(MODEL_DATA_H), exist_ok=True)
    with open(MODEL_DATA_H, "w") as f:
        f.write(header)
    with open(MODEL_DATA_CC, "w") as f:
        f.write(source)

    print(f"Wrote {MODEL_DATA_H}")
    print(f"Wrote {MODEL_DATA_CC}")


def main():
    tflite_bytes = convert_to_int8()
    emit_c_arrays(tflite_bytes)
    print("\nDone. Next: build the ESP32 firmware —")
    print("  cd esp32/naad_kws && idf.py set-target esp32 && idf.py build flash monitor")


if __name__ == "__main__":
    main()
