// AUTO-GENERATED by training/convert.py — do not edit by hand.
// Regenerate with: python convert.py
#ifndef NAAD_MODEL_DATA_H_
#define NAAD_MODEL_DATA_H_

#include <cstdint>

extern const unsigned char g_naad_kws_model_data[];
extern const unsigned int g_naad_kws_model_data_len;

#endif  // NAAD_MODEL_DATA_H_
